

     version: 2

     jobs:
       deploy:
         machine:
           enabled: true
         steps:
           - run:
               name: Deploy Over SSH
               command: |
                 ssh $SSH_USER@$SSH_HOST "/home/dep/iota-up/server/deploy.sh"

     workflows:
       version: 2
       build-and-deploy:
         jobs:
           - deploy:
               filters:
                 branches:
                   only: main # only deploy on the master branch



